name: 'Setup Android Environment'
description: 'Sets up Java, Gradle and local.properties for Android projects'
inputs:
  cache-read-only:
    description: 'Whether the Gradle cache should be read-only'
    required: false
    default: 'false'
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
    - uses: gradle/actions/setup-gradle@v4
      continue-on-error: true
      with:
        gradle-version: wrapper
        cache-overwrite-existing: true
        cache-read-only: ${{ inputs.cache-read-only }}

    - name: Create local.properties
      shell: bash
      run: echo "sdk.dir=$ANDROID_HOME" > ./local.properties
