ENV['SWIFT_VERSION'] = '5'

target 'DevFest Nantes' do
  use_frameworks!
  platform :ios, '15'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesCombine', '0.12.5'
  pod 'KMPNativeCoroutinesAsync'
  pod "NSLogger/Swift"
  pod "URLImage"
  pod 'SwiftGen', '~> 6.6'
  # Firebase
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
end

target 'DevFest NantesTests' do
    inherit! :search_paths

end
