target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'store', :path => '../store'
  pod 'storeMocked', :path => '../storeMocked'
  pod 'KMPNativeCoroutinesCombine', '0.12.5'
end