source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
 end
end

ENV['SWIFT_VERSION'] = '5'
use_frameworks!
platform :ios, '15.0'

target 'DevFest Nantes' do
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-34'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-34'
  pod "NSLogger/Swift"
  pod "URLImage"
  pod 'SwiftGen', '~> 6.6'
  # Firebase
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
end

target 'DevFest NantesTests' do
    inherit! :search_paths

end