name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  JAVA_VERSION: 17

jobs:
  checks:
    name: Checks Linters
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache-read-only: 'true'

      - name: Check Detekt
        run: ./gradlew detekt

      - name: Check lint
        run: ./gradlew lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache-read-only: 'true'

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        api-level: [34]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache-read-only: 'true'

      # API 30+ emulators only have x86_64 system images.
      - name: Get AVD info
        uses: ./.github/actions/get-avd-info
        id: avd-info
        with:
          api-level: ${{ matrix.api-level }}

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ steps.avd-info.outputs.arch }}
          target: ${{ steps.avd-info.outputs.target }}
          script: ./gradlew connectedDebugAndroidTest

  build-debug:
    name: Build debug
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-setup
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache-read-only: 'false'

      - name: Build Debug APK
        run: ./gradlew assembleDebug
