name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  ios-build:
    name: iOS Build Check
    runs-on: macos-15
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: 'true'
      
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > ./local.properties
      
      - name: Install SwiftGen
        run: brew install swiftgen
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Show available simulators
        run: xcrun simctl list devices available
      
      - name: Build shared framework
        run: ./gradlew :shared:embedAndSignAppleFrameworkForXcode
      
      - name: Generate SwiftGen files
        working-directory: iosApp/iosApp/SwiftGen
        run: swiftgen config run
      
      - name: Build iOS App for Simulator
        run: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -scheme "DevFest Nantes" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
            -derivedDataPath build \
            build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE=""
